engine = ink
title = Cloak of Darkness (Ink)
author = An Interactive Fiction
description = The classic IF engine test, implemented in Ink.
binary = cloak-of-darkness.json
source = cloak-of-darkness.ink
tags = cloak, demo, classic
